# SPDX-FileCopyrightText: 2025 Zextras <https://www.zextras.com>
# SPDX-License-Identifier: GPL-2.0-only

# Carbonio MTA service user and group
# See sysusers.d(5) for format

g carbonio-mta -
u carbonio-mta - "Carbonio MTA Service" - /sbin/nologin
