#!/bin/bash

SERVICE_NAME="carbonio-mta"

if [[ $(id -u) -ne 0 ]]; then
  echo "Please run as root"
  exit 1
fi

if [[ "$1" != "setup" ]]; then
  echo "Syntax: ${SERVICE_NAME} <setup> to automatically setup the service"
  exit 1;
fi

# decrypt the bootstrap token, asking the password to the sys admin
# --setup check for SETUP_CONSUL_TOKEN env. variable and uses it
# to avoid re-asking for the password multiple times
echo -n "insert the cluster credential password: "
export CONSUL_HTTP_TOKEN=$(service-discover bootstrap-token --setup)
EXIT_CODE="$?"
echo ""
if [[ "${EXIT_CODE}" != "0" ]]; then
  echo "cannot access to bootstrap token"
  exit 1;
fi
# limit secret visibility as much as possible
export -n SETUP_CONSUL_TOKEN

POLICY_NAME="${SERVICE_NAME}-policy"
POLICY_DESCRIPTION='Carbonio MTA service policy for config generation and for sidecar proxy'
POLICY_RULES="$(cat <<EOF
"key_prefix" = {
  "carbonio-mta/" = {
    "policy" = "read"
  }
}
"node_prefix" = {
  "" = {
    "policy" = "read"
  }
}
"service" = {
  "${SERVICE_NAME}" = {
    "policy" = "write"
  }
  "${SERVICE_NAME}-sidecar-proxy" = {
    "policy" = "write"
  }
}
EOF
)"

# create or update policy for the specific service (this will be shared across cluster)
consul acl policy create -name "${POLICY_NAME}" -description "${POLICY_DESCRIPTION}" -rules "${POLICY_RULES}" >/dev/null 2>&1
if [[ "$?" != "0" ]]; then
    consul acl policy update -no-merge -name "${POLICY_NAME}" -description "${POLICY_DESCRIPTION}" -rules "${POLICY_RULES}"
    if [[ "$?" != "0" ]]; then
      echo "Setup failed: Cannot update policy for ${POLICY_NAME}"
      exit 1
    fi
fi

if [[ ! -f "/etc/zextras/${SERVICE_NAME}/token" ]]; then
    # create the token
    consul acl token create -format json -policy-name "${POLICY_NAME}" -description "Token for ${SERVICE_NAME}/$(hostname -A)" |
      jq -r '.SecretID' > /etc/zextras/${SERVICE_NAME}/token;
    chown carbonio-mta:carbonio-mta /etc/zextras/${SERVICE_NAME}/token
    chmod 0600 /etc/zextras/${SERVICE_NAME}/token
fi

consul reload

# limit token visibility as much as possible
export -n CONSUL_HTTP_TOKEN

systemctl restart ${SERVICE_NAME}-sidecar.service
