#!/bin/bash

SERVICE_NAME="carbonio-mta"
SERVICE_USER="carbonio-mta"
SERVICE_GROUP="carbonio-mta"
SERVICE_BASE_DIR="/etc/carbonio/mta/service-discover/"

if [[ $(id -u) -ne 0 ]]; then
  echo "Please run as root"
  exit 1
fi

if [[ "$1" != "setup" ]]; then
  echo "Syntax: '${SERVICE_NAME} setup' to automatically configure the service"
  exit 1;
fi

# Decrypt the bootstrap token, asking the password to the sys admin
# --setup check for SETUP_CONSUL_TOKEN env. variable and uses it
# to avoid re-asking for the password
echo -n "Insert the cluster credential password: "
export CONSUL_HTTP_TOKEN=$(service-discover bootstrap-token --setup)
EXIT_CODE="$?"
echo ""
if [[ "${EXIT_CODE}" != "0" ]]; then
  echo "Cannot access to bootstrap token"
  exit 1;
fi
# Limit secret visibility as much as possible
export -n SETUP_CONSUL_TOKEN

POLICY_NAME="${SERVICE_NAME}-policy"
POLICY_DESCRIPTION='Carbonio MTA service policy for service and sidecar proxy'

# Create or update policy for the specific service (this will be shared across cluster)
consul acl policy create -name "${POLICY_NAME}" -description "${POLICY_DESCRIPTION}" -rules @${SERVICE_BASE_DIR}/policies.json >/dev/null 2>&1
if [[ "$?" != "0" ]]; then
    consul acl policy update -no-merge -name "${POLICY_NAME}" -description "${POLICY_DESCRIPTION}" -rules @${SERVICE_BASE_DIR}/policies.json
    if [[ "$?" != "0" ]]; then
      echo "Setup failed: Cannot update policy ${POLICY_NAME}"
      exit 1
    fi
fi

trap 'echo Script for mta terminated with error' EXIT
set -e

# Declare the service protocol
consul config write ${SERVICE_BASE_DIR}/service-protocol.json

# Allow other services to contact this service (nothing at the moment)

# Create ACL token
if [[ ! -f "${SERVICE_BASE_DIR}/token" ]]; then
    # create the token
    consul acl token create -format json -policy-name "${POLICY_NAME}" -description "Token for ${SERVICE_NAME}/$(hostname -A)" |
      jq -r '.SecretID' > ${SERVICE_BASE_DIR}/token;
    chown ${SERVICE_USER}:${SERVICE_GROUP} ${SERVICE_BASE_DIR}/token
    chmod 0600 ${SERVICE_BASE_DIR}/token
    # To pass the token we need to inject it to a env. variable
    # since it doesn't accept a file as an argument
    mkdir -p /etc/systemd/system/${SERVICE_NAME}.service.d/
    cat >/etc/systemd/system/${SERVICE_NAME}.service.d/override.conf <<EOF
    [Service]
    Environment="CONSUL_HTTP_TOKEN=$(cat ${SERVICE_BASE_DIR}/token)"
EOF
    chmod 0600 /etc/systemd/system/${SERVICE_NAME}.service.d/override.conf
    systemctl daemon-reload
fi

consul reload

# limit token visibility as much as possible
export -n CONSUL_HTTP_TOKEN

systemctl restart ${SERVICE_NAME}-sidecar.service

trap - EXIT